### ISSUE TITLE
Make working example

### ISSUE THREAD

**Issue by ochibani** [oknozor/stray#3]
The GTK example is not really working.

**Comment by oknozor** [comment]
It's working. can you elaborate ? 

![screenshot-2022-11-06T12:03:19](https://user-images.githubusercontent.com/24563836/200167018-4e141889-54a8-4c42-9914-fc008be81755.png)

**Comment by ochibani** [comment]
My bad, I think testing it on gnome was the wrong idea.
It's working on swaywm.

**Comment by ruanyouxing** [comment]
> It's working. can you elaborate ?
> 
> ![screenshot-2022-11-06T12:03:19](https://user-images.githubusercontent.com/24563836/200167018-4e141889-54a8-4c42-9914-fc008be81755.png)

It's turned black on bspwm I have no idea
![image](https://user-images.githubusercontent.com/87190231/208930259-e39be740-c8b6-44ef-9ee3-d29909d6da68.png)
