### ISSUE TITLE
Creating host causes panic

### ISSUE THREAD

**Issue by JakeStanger** [oknozor/stray#6]
Creating a host now consistently causes a panic due to an unwrap, which appears to be caused by the DBus connection:

```
create tray
create host
thread 'mainthread '' panicked at 'tokio-runtime-workercalled `Result::unwrap()` on an `Err` value: DbusError(Variant(Message("invalid value: string \"()\", expected at least one field signature between `(` and `)`")))' panicked at '', Unexpected StatusNotifierError : DbusError(Variant(Message("invalid value: string \"()\", expected at least one field signature between `(` and `)`")))src/main.rs', :/home/jake/.cargo/registry/src/github.com-1ecc6299db9ec823/stray-0.1.3/src/notifier_watcher/mod.rs12::3760:
22
stack backtrace:
thread 'tokio-runtime-worker' panicked at 'Unexpected error while dispatching UI command: DbusError(Variant(Message("invalid value: string \"()\", expected at least one field signature between `(` and `)`")))', /home/jake/.cargo/registry/src/github.com-1ecc6299db9ec823/stray-0.1.3/src/notifier_watcher/mod.rs:45:22
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1090:23
   4: tray_test::main::{{closure}}
             at ./src/main.rs:12:20
```

Code to replicate:

```rs
use stray::StatusNotifierWatcher;
use tokio::sync::mpsc;

#[tokio::main]
async fn main() {
    let (_tx, rx) = mpsc::channel(32);

    println!("create tray");
    let tray = StatusNotifierWatcher::new(rx).await.unwrap();

    println!("create host");
    let host = tray.create_notifier_host("test").await.unwrap();
}
```

This was raised by users of ironbar in this issue: https://github.com/JakeStanger/ironbar/issues/166
It is occurring on both NixOS and Arch, on both Sway and Hyprland (both stable and `-git`).

The reasoning why this has started occurring is unclear.

---

As a slight aside, ideally `stray` should not panic at all. The Rust docs advise against using `unwrap()` except for prototyping, preferring to use `expect` where a panic really is the right solution, and better handling the error in all other cases. 

In a library, all errors should really be bubbled up as a `Result` returned to the consumer, allowing them to handle it appropriately (currently Ironbar hard-crashes if you use the tray module, which I cannot control).

**Comment by oknozor** [comment]
Hey @JakeStanger sorry for the delay, I did not have a lot of time to maintain stray lately but I should be able to fix the unwrapping soon. Maybe you'd want to have co-maintainer permissions to speed things up ?  

Let's me know if you would be interested.

**Comment by JakeStanger** [comment]
Hey no worries at all, appreciate you're busy :) I'd be happy to take on that role, and then when I find some time myself I can help clean up some rough edges (and figure out why DBus has given up accepting the connection...). Cheers!

**Comment by JakeStanger** [comment]
@oknozor Thanks for adding me as a maintainer, I'm pretty limited on time myself now but will do what I can when I can. 

Would you be willing to add me to as one on crates.io too so I can manage releases?
